name: SCIP
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Generate SCIP data
        uses: sourcegraph/scip-go-action@master
        with:
          verbose: "true"
      - name: Upload SCIP data
        uses: sourcegraph/lsif-upload-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
